/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CartasUtilidades;

/**
 *
 * @author carlo
 */
import javax.swing.*;
import java.util.*;
public class Tablero extends javax.swing.JFrame {

    /**
     * Creates new form Tablero
     */
    
    Jugador Jugador1;
    Jugador Jugador2;
    ArrayList<JLabel> CartasPrimerJugador;
    ArrayList<JLabel> CartasSegundoJugador;
    
    public Tablero() {
        CartasPrimerJugador = new ArrayList<>();
        CartasSegundoJugador = new ArrayList<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\UNO\\src\\Imagenes\\BotonUNITO.png")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 540, 190, 150);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cambio");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(950, 320, 140, 60);

        jLabel32.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\UNO\\src\\Imagenes\\BocaAbajo.png")); // NOI18N
        jLabel32.setText("jLabel2");
        getContentPane().add(jLabel32);
        jLabel32.setBounds(1020, 0, 110, 160);
        getContentPane().add(jLabel31);
        jLabel31.setBounds(640, 264, 120, 170);
        getContentPane().add(jLabel30);
        jLabel30.setBounds(460, 284, 90, 130);

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\UNO\\src\\Imagenes\\BocaAbajo.png")); // NOI18N
        jLabel13.setText("jLabel2");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(1000, 530, 110, 160);

        jLabel29.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\UNO\\src\\Imagenes\\BocaAbajo.png")); // NOI18N
        jLabel29.setText("jLabel2");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(950, 530, 110, 160);

        jLabel28.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\UNO\\src\\Imagenes\\BocaAbajo.png")); // NOI18N
        jLabel28.setText("jLabel2");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(900, 530, 110, 160);

        jLabel27.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\UNO\\src\\Imagenes\\BocaAbajo.png")); // NOI18N
        jLabel27.setText("jLabel2");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(850, 530, 110, 160);

        jLabel26.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\UNO\\src\\Imagenes\\BocaAbajo.png")); // NOI18N
        jLabel26.setText("jLabel2");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(800, 530, 110, 160);

        jLabel25.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\UNO\\src\\Imagenes\\BocaAbajo.png")); // NOI18N
        jLabel25.setText("jLabel2");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(750, 530, 110, 160);

        jLabel24.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\UNO\\src\\Imagenes\\BocaAbajo.png")); // NOI18N
        jLabel24.setText("jLabel2");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(700, 530, 110, 160);

        jLabel23.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\UNO\\src\\Imagenes\\BocaAbajo.png")); // NOI18N
        jLabel23.setText("jLabel2");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(970, 0, 110, 160);

        jLabel22.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\UNO\\src\\Imagenes\\BocaAbajo.png")); // NOI18N
        jLabel22.setText("jLabel2");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(920, 0, 110, 160);

        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\UNO\\src\\Imagenes\\BocaAbajo.png")); // NOI18N
        jLabel21.setText("jLabel2");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(870, 0, 110, 160);

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\UNO\\src\\Imagenes\\BocaAbajo.png")); // NOI18N
        jLabel20.setText("jLabel2");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(820, 0, 110, 160);

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\UNO\\src\\Imagenes\\BocaAbajo.png")); // NOI18N
        jLabel19.setText("jLabel2");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(770, 0, 110, 160);

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\UNO\\src\\Imagenes\\BocaAbajo.png")); // NOI18N
        jLabel18.setText("jLabel2");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(720, 0, 110, 160);

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\UNO\\src\\Imagenes\\BocaAbajo.png")); // NOI18N
        jLabel17.setText("jLabel2");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(650, 530, 110, 160);

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\UNO\\src\\Imagenes\\BocaAbajo.png")); // NOI18N
        jLabel16.setText("jLabel2");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(600, 530, 110, 160);

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\UNO\\src\\Imagenes\\BocaAbajo.png")); // NOI18N
        jLabel15.setText("jLabel2");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(550, 530, 110, 160);

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\UNO\\src\\Imagenes\\BocaAbajo.png")); // NOI18N
        jLabel14.setText("jLabel2");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(500, 530, 110, 160);

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\UNO\\src\\Imagenes\\BocaAbajo.png")); // NOI18N
        jLabel12.setText("jLabel2");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(450, 530, 110, 160);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\UNO\\src\\Imagenes\\BocaAbajo.png")); // NOI18N
        jLabel11.setText("jLabel2");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(400, 530, 110, 160);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\UNO\\src\\Imagenes\\BocaAbajo.png")); // NOI18N
        jLabel10.setText("jLabel2");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(350, 530, 110, 160);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\UNO\\src\\Imagenes\\BocaAbajo.png")); // NOI18N
        jLabel9.setText("jLabel2");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(670, 0, 110, 160);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\UNO\\src\\Imagenes\\BocaAbajo.png")); // NOI18N
        jLabel8.setText("jLabel2");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(620, 0, 110, 160);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\UNO\\src\\Imagenes\\BocaAbajo.png")); // NOI18N
        jLabel7.setText("jLabel2");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(570, 0, 110, 160);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\UNO\\src\\Imagenes\\BocaAbajo.png")); // NOI18N
        jLabel6.setText("jLabel2");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(520, 0, 110, 160);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\UNO\\src\\Imagenes\\BocaAbajo.png")); // NOI18N
        jLabel5.setText("jLabel2");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(470, 0, 110, 160);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\UNO\\src\\Imagenes\\BocaAbajo.png")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(420, 0, 110, 160);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\UNO\\src\\Imagenes\\BocaAbajo.png")); // NOI18N
        jLabel4.setText("jLabel2");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(370, 0, 110, 160);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\UNO\\src\\Imagenes\\Tablerin.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1203, 695);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        CartasPrimerJugador.add(jLabel10);
        CartasPrimerJugador.add(jLabel11);
        CartasPrimerJugador.add(jLabel12);
        CartasPrimerJugador.add(jLabel14);
        CartasPrimerJugador.add(jLabel15);
        CartasPrimerJugador.add(jLabel16);
        CartasPrimerJugador.add(jLabel17);
        CartasPrimerJugador.add(jLabel24);
        CartasPrimerJugador.add(jLabel25);
        CartasPrimerJugador.add(jLabel26);
        CartasPrimerJugador.add(jLabel27);
        CartasPrimerJugador.add(jLabel28);
        CartasPrimerJugador.add(jLabel29);
        CartasPrimerJugador.add(jLabel13);
        
        CartasSegundoJugador.add(jLabel4);
        CartasSegundoJugador.add(jLabel2);
        CartasSegundoJugador.add(jLabel5);
        CartasSegundoJugador.add(jLabel6);
        CartasSegundoJugador.add(jLabel7);
        CartasSegundoJugador.add(jLabel8);
        CartasSegundoJugador.add(jLabel9);
        CartasSegundoJugador.add(jLabel18);
        CartasSegundoJugador.add(jLabel19);
        CartasSegundoJugador.add(jLabel20);
        CartasSegundoJugador.add(jLabel21);
        CartasSegundoJugador.add(jLabel22);
        CartasSegundoJugador.add(jLabel23);
        CartasSegundoJugador.add(jLabel32);
        
        Jugador1 = new Jugador();
        Jugador2 = new Jugador();
        
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        System.out.println("Hola");
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        System.out.println("Hola");
    }//GEN-LAST:event_jButton1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablero().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
